# Generated by Django 4.0.4 on 2022-05-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url360p', models.CharField(max_length=1000)),
                ('url480p', models.CharField(max_length=1000)),
                ('url720p', models.CharField(max_length=1000)),
                ('url1080p', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('PROCESSING', 'PROCESSING')], default='PROCESSING', max_length=12)),
                ('message', models.CharField(max_length=1000)),
                ('original_res', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
