# Generated by Django 4.0.4 on 2022-05-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PROCESSING', 'PROCESSING'), ('FAILED', 'FAILED')], default='PROCESSING', max_length=12),
        ),
    ]
