# Generated by Django 4.0.4 on 2022-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_video_file_alter_video_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='filename',
        ),
        migrations.AlterField(
            model_name='video',
            name='message',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='original_res',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED')], default='PROCESSING', max_length=12),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='url1080p',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='url360p',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='url480p',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='url720p',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
