# Generated by Django 4.0.4 on 2022-05-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_rename_video_file_video_filename_alter_video_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='filename',
            field=models.FileField(default=None, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='message',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='original_res',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PROCESSING', max_length=12),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url1080p',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url360p',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url480p',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url720p',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
