# Generated by Django 4.0.4 on 2022-06-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_video_filename_alter_video_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED')], default='PROCESSING', max_length=12),
        ),
    ]
